title: Ouroboros
description: "Records how the code actually ran: calls, arguments, results, exceptions, durations"
lang: en

theme: jekyll-theme-minimal

url: https://digitable-lol.github.io
baseurl: /ouroboros

defaults:
  - scope:
      path: ""
    values:
      layout: default
