title: Уроборос
description: "Записывает, как код на самом деле исполнялся: вызовы, доводы, результаты, исключения, длительности"
lang: ru

theme: jekyll-theme-minimal

url: https://digitable-lol.github.io
baseurl: /ouroboros

defaults:
  - scope:
      path: ""
    values:
      layout: default
